[package]
name = "platform-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
dialoguer = "0.11.0"
handlebars = "5.1.2"
include_dir = "0.7.4"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
